version: "3.9"
services:
  trino:
    ports:
      - "8088:8080"
    image: "trinodb/trino:435"
    volumes:
      - ./docker/trino/etc:/usr/lib/trino/etc:ro
      - ./docker/trino/catalog:/etc/trino/catalog

  postgres_test:
    ports:
      - "5432:5432"
    image: postgres:11
    container_name: postgres_test
    environment:
      POSTGRES_USER: dbt-trino
      POSTGRES_PASSWORD: dbt-trino

  metastore_db:
    image: postgres:11
    hostname: metastore_db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore

  hive-metastore:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    depends_on:
      - metastore_db

  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2022-05-26T05-48-41Z'
    container_name: minio
    ports:
      - '9000:9000'
      - '9009:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"

  # This job will create the "datalake" bucket on Minio
  mc-job:
    image: 'minio/mc:RELEASE.2022-05-09T04-08-26Z'
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc config --quiet host add minio-test http://minio:9000 minio minio123;
      /usr/bin/mc mb --quiet minio-test/datalake
      /usr/bin/mc mb --quiet minio-test/airflow-logs
      /usr/bin/mc mb --quiet minio-test/docs
      "
    depends_on:
      - minio

  trino-init:
      build: ./trino_cli
      container_name: trino-init
      environment:
        CONNECTION_URI: http://trino:8080
        CONNECTION_USER: admin
        CONNECTION_PW:
      entrypoint: |
        /bin/bash -c "
        ./trino --server 'http://trino:8080' --catalog hive --execute 'create schema if not exists import;'
        ./trino --server 'http://trino:8080' --catalog hive --execute 'create schema if not exists raw;'
        ./trino --server 'http://trino:8080' --catalog hive --execute 'create schema if not exists stage;'
        ./trino --server 'http://trino:8080' --catalog hive --execute 'create schema if not exists business;'
        "
      depends_on:
          - trino 

  datagen:
    build: ./source_data
    container_name: datagen
    command: ["python", "data.py"]

networks:
  default:
    name: data_platform
